{% set name = "colander" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colander-{{ version }}.tar.gz
  sha256: 419cd68178d2ee6ee4cae5d5cb1830725634b0a2840917156e89eb2592237ef3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - iso8601
    - setuptools >=11.3
    - translationstring

test:
  imports:
    - colander
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Pylons/colander
  summary: A simple schema-based serialization and deserialization library
  license: BSD-3-Clause-Modification
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
